#!/usr/bin/env python3
"""
strand_stratified_comparison.py — why fixing a bug REMOVED catalogue matches.

THE QUESTION
------------
Correcting a defect in the peptide generator cut parental's distinct catalogue
matches from 288 to 130, with no new match appearing anywhere. A fix that only
takes away is counter-intuitive enough that it needs an explanation which can be
checked, not asserted.

THE ANSWER, AND HOW IT IS TESTED
--------------------------------
If the lost matches were a shared methodological signature — both the cell-line
candidates and the patient catalogue generated by the same tool, sharing the same
defect — then losses must be confined to the strand configurations the defect
touched. Fusions with no minus-strand partner should be untouched.

That is a falsifiable prediction, and stratifying by the strand pair tests it.
`truncate_cds` is called for both the 5' and 3' side of every fusion, so a fusion
is affected if EITHER partner is on the minus strand; the plus/plus class is the
internal control.

Emits markdown; render with tools/build_summary_html.py.

    python tools/strand_stratified_comparison.py --out strand_comparison.md
"""
from __future__ import annotations

import argparse
import pathlib

import pandas as pd

REPO = pathlib.Path(__file__).resolve().parent.parent


def matches(directory: str, run: str) -> pd.DataFrame:
    path = REPO / directory / run / "stage3_matches.tsv"
    return pd.read_csv(path, sep="\t", low_memory=False) if path.exists() \
        else pd.DataFrame()


def candidates(directory: str, run: str) -> pd.DataFrame:
    path = next((REPO / directory / run).glob("*.all_neopeptides.txt"), None)
    return pd.read_csv(path, sep="\t", low_memory=False) if path \
        else pd.DataFrame()


def pair_table(before: pd.DataFrame, lost: set) -> str:
    """Retention by (5' strand, 3' strand) — the test of the explanation."""
    unique = before.drop_duplicates("peptide")
    rows = []
    for (s1, s2), group in unique.groupby(["strand1", "strand2"], dropna=False):
        total = len(group)
        gone = int(group["peptide"].isin(lost).sum())
        rows.append((s1, s2, total, gone, total - gone,
                     100 * (total - gone) / total if total else float("nan")))
    rows.sort(key=lambda r: -r[2])

    lines = ["| 5′ strand | 3′ strand | matches before | lost | survived | retained |",
             "|---|---|---|---|---|---|"]
    for s1, s2, total, gone, kept, pct in rows:
        emphasis = "**" if (s1 == "+" and s2 == "+") else ""
        lines.append(f"| `{s1}` | `{s2}` | {total:,} | {gone:,} | "
                     f"{emphasis}{kept:,}{emphasis} | "
                     f"{emphasis}{pct:.0f}%{emphasis} |")
    return "\n".join(lines)


def frame_table(before: pd.DataFrame, after: pd.DataFrame) -> str:
    """Share of Start-loss by strand, in the whole candidate universe."""
    lines = ["| 5′ strand | candidates before | `Start-loss` before "
             "| candidates after | `Start-loss` after |", "|---|---|---|---|---|"]
    for strand in ("-", "+"):
        row = [f"| `{strand}` "]
        for table in (before, after):
            subset = table[table.get("strand1") == strand] \
                if "strand1" in table.columns else table.iloc[0:0]
            share = (subset["frame_effect"] == "Start-loss").mean() \
                if len(subset) and "frame_effect" in subset.columns else float("nan")
            row.append(f"| {len(subset):,} | "
                       + ("—" if pd.isna(share) else f"{100 * share:.1f}%") + " ")
        lines.append("".join(row) + "|")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--before", default="results")
    parser.add_argument("--after", default="results_patch002")
    parser.add_argument("--run", default="parental_noPON")
    parser.add_argument("--out", default="strand_comparison.md")
    args = parser.parse_args()

    before, after = matches(args.before, args.run), matches(args.after, args.run)
    if before.empty:
        raise SystemExit(f"no stage3_matches.tsv in {args.before}/{args.run}")

    kept_set, before_set = set(after.get("peptide", [])), set(before["peptide"])
    lost, new = before_set - kept_set, kept_set - before_set
    cand_before, cand_after = candidates(args.before, args.run), \
        candidates(args.after, args.run)

    unique = before.drop_duplicates("peptide")
    by_strand = {
        s: (int((unique["strand1"] == s).sum()),
            int(unique[unique["strand1"] == s]["peptide"].isin(lost).sum()))
        for s in ("-", "+")}

    def retained(strand: str) -> float:
        # Percentage of that strand's matches surviving the patch.
        total, gone = by_strand[strand]
        return 100 * (total - gone) / total if total else float("nan")

    # The minus/minus class specifically: the bulk of the data, and the only
    # affected class not wiped out entirely, so its retention is the informative
    # one. Computed here rather than inline — an earlier version used an `and`
    # expression that returned the right number by accident.
    both_minus = unique[(unique["strand1"] == "-") & (unique["strand2"] == "-")]
    mm_retained = (100 * (len(both_minus)
                          - int(both_minus["peptide"].isin(lost).sum()))
                   / len(both_minus)) if len(both_minus) else float("nan")

    document = f"""# Why correcting the defect *removed* catalogue matches

Patch 002 repaired the 5′ coding segment of minus-strand transcripts. Applying it
cut `{args.run}`'s distinct catalogue matches from **{len(before_set):,} to
{len(kept_set):,}** — and produced **{len(new)} new ones**.

A fix that only takes away is counter-intuitive. This tests the explanation
rather than asserting it.

## The explanation

Before the patch, a minus-strand transcript contributed an **empty 5′ head** to
its fusion when the breakpoint fell in an intron, and a head of the wrong length
when it fell in an exon. The resulting "fusion protein" was largely the 3′
partner's sequence translated from an arbitrary point — a specific, degenerate
class of sequence produced by the defect rather than by biology.

**The patient catalogue was built with the same tool family.** If it carries the
same defect, then both sides were producing that same degenerate class, and they
matched each other on it. Correcting one side removes the shared signature, and
those matches disappear — not because sensitivity was lost, but because they were
never evidence of shared biology.

## The prediction this makes

If the lost matches are a shared artefact, the losses must be **confined to the
strand configurations the defect touched**. `truncate_cds` runs on both the 5′
and the 3′ side of every fusion, so a fusion is affected when **either** partner
lies on the minus strand. Fusions with two plus-strand partners were never
broken, and must therefore be untouched.

That class is the internal control. If it loses matches too, the explanation is
wrong.

## The result

{pair_table(before, lost)}

**Every plus/plus fusion survived.** The classes with a minus-strand partner on
one side only were removed entirely, and the minus/minus class — the bulk of the
data — retained {mm_retained:.0f}%.

The eight losses whose 5′ side is on the plus strand are not exceptions: every
one of them has a **minus-strand 3′ partner**, which is precisely the other route
by which the defect reached a fusion.

## By 5′ strand alone

| 5′ strand | matches before | lost | survived | retained |
|---|---|---|---|---|
| `-` | {by_strand['-'][0]:,} | {by_strand['-'][1]:,} | {by_strand['-'][0] - by_strand['-'][1]:,} | {retained('-'):.0f}% |
| `+` | {by_strand['+'][0]:,} | {by_strand['+'][1]:,} | {by_strand['+'][0] - by_strand['+'][1]:,} | {retained('+'):.0f}% |

Reading this column alone is misleading — it hides that the plus-strand losses
are all mixed-strand fusions. The pair table above is the one to quote.

## The defect's signature, before and after

{frame_table(cand_before, cand_after)}

`Start-loss` is upstream's own low-reliability flag: the start codon is gone and
the tool falls back to the next ATG. Its collapse on the minus strand, with the
plus strand unmoved, is what identifies the change as strand-specific rather than
a general shift.

## What this does and does not establish

**Establishes** that the removed matches were concentrated exactly where the
defect operated, and absent where it did not. That is what a shared
methodological artefact looks like, and it is not what a loss of genuine
sensitivity would look like — a real signal would not respect strand
configuration so precisely.

**Does not establish** that the {len(kept_set):,} surviving matches are genuine.
They are simply no longer explained by *this* defect.

**And {len(kept_set):,} is a floor, not a ceiling.** The patient catalogue was
built with the same unpatched tool — verified, not assumed: its source file shows
79.2% `Start-loss` on the minus strand against 13.0% on the plus, this
repository's own pre-patch signature. So a genuine minus-strand neoantigen is
**not in the catalogue under its true sequence**, and a corrected peptide cannot
match it. Those recurrences are currently unfindable, and **rebuilding the
catalogue can only add them**. Until that happens, any statement that recurrence
is low carries this caveat.

**Does not change the headline.** No candidate satisfied every criterion before
the patch, and none does after.

---

Generated by `tools/strand_stratified_comparison.py` from
`{args.before}/` and `{args.after}/`. Reproduce with:

```bash
python tools/strand_stratified_comparison.py --run {args.run}
python tools/build_summary_html.py --doc {args.out}
```
"""

    out = REPO / args.out
    out.write_text(document)
    print(f"  wrote {args.out}")
    print(f"  {len(before_set):,} matches before, {len(kept_set):,} after, "
          f"{len(lost):,} lost, {len(new)} new")


if __name__ == "__main__":
    main()
